name: Check Website Daily

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Chrome and dependencies
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
          python -m pip install --upgrade pip
          pip install selenium requests webdriver_manager

      - name: Run check
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          SEARCH_TEXT: ${{ secrets.SEARCH_TEXT }}
          INITIAL_URL: ${{ secrets.INITIAL_URL}}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python check_website.py

      - name: Upload page content
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: page-content
          path: page.html
          retention-days: 5
          if-no-files-found: warn

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: page.png
          retention-days: 5 # Keep screenshots for 5 days
          if-no-files-found: warn # Warn but don't fail if screenshot isn't created
