name: Check Website Daily

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggers

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Run check
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          SEARCH_TEXT: ${{ secrets.SEARCH_TEXT }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} # Optional
        run: python check_website.py
